#ifndef FREETYPEWRAPER_GLOBAL_H
#define FREETYPEWRAPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FREETYPEWRAPER_LIBRARY)
#  define FREETYPEWRAPER_EXPORT Q_DECL_EXPORT
#else
#  define FREETYPEWRAPER_EXPORT Q_DECL_IMPORT
#endif

#endif // FREETYPEWRAPER_GLOBAL_H
